image: node:latest

stages:
  - install
  - buildDeploy

cache:
  paths:
    - node_modules/

installDependencies:
  stage: install
  script:
    - npm install
  artifacts:
    paths:
      - node_modules/

buildDeploy:
  stage: buildDeploy
  script: 
    - apt-get update -qy
    - apt-get install -y lftp
    - npm run build
    - cd src/.vuepress/dist
    - lftp -e "set ssl:verify-certificate no; open $FTP_HOST; user $FTP_USER $FTP_PASS; mirror -e -R -p ./ artefact-labs/docs; bye"
    #- lftp -u $FTP_USER,$FTP_PASS $FTP_HOST -e "set ftp:ssl-allow no ; mirror -e -R -p ./ artefact-labs/docs ; quit"
    - echo "deployment complete"
  # specify environment this job is using
  environment:
    name: staging
    url: https://doc.artefact-labs.com
  # only run on dev branch
  only:
    - master