image: node:latest

stages:
  - build
  - deploy

cache:
  paths:
    - node_modules/

install_dependencies:
  stage: build
  script:
    - npm install
  artifacts:
    paths:
      - node_modules/

deployment:
  stage: deploy
  script: 
    - npm run docs:build
    - lftp -u $FTP_USER,$FTP_PASS $FTP_HOST -e "set ftp:ssl-allow no ; mirror -e -R -p ./dist artefact-labs/docs ; quit"
    - echo "deployment complete"
  # specify environment this job is using
  environment:
    name: staging
    url: https://doc.artefact-labs.com
  # only run on dev branch
  only:
    - master