image: node:latest

stages:
  - install
  - build_deploy

cache:
  paths:
    - node_modules/

install_dependencies:
  stage: build
  script:
    - npm install
  artifacts:
    paths:
      - node_modules/

build_deploy:
  stage: build_deploy
  script: 
    - apt-get update -qy
    - apt-get install -y lftp
    - npm run build
    - cd src/.vuepress/dist
    - lftp -u $FTP_USER,$FTP_PASS $FTP_HOST -e "set ftp:ssl-allow no ; mirror -e -R -p ./ artefact-labs/docs ; quit"
    - echo "deployment complete"
  # specify environment this job is using
  environment:
    name: staging
    url: https://doc.artefact-labs.com
  # only run on dev branch
  only:
    - master