image: ubuntu:18.04

before_script:
  - apt-get update -qy
  - apt-get install -y lftp
  - node -v
  - npm install
  - npm run docs:build

deploy:
  script:
    - lftp -u $FTP_USER,$FTP_PASS $FTP_HOST -e "set ftp:ssl-allow no ; mirror -e -R -p ./dist artefact-labs/docs ; quit"
    - echo "deployment complete"
  # specify environment this job is using
  environment:
    name: staging
    url: https://doc.artefact-labs.com
  # only run on dev branch
  only:
    - master